apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
      volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
      meta.helm.sh/release-name: dedicated-server-deployment
      meta.helm.sh/release-namespace: dedicated-server-deployment
  labels:
      app.kubernetes.io/managed-by: Helm
  name: ebs-claim
  namespace: servers
spec:
  volumeName: ebs-vol
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 95Gi
  
