apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
      meta.helm.sh/release-name: dedicated-server-deployment
      meta.helm.sh/release-namespace: dedicated-server-deployment
  labels:
      app.kubernetes.io/managed-by: Helm
  name: efs-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0747d6b7be774ae1c