apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
      meta.helm.sh/release-name: dedicated-server-deployment
      meta.helm.sh/release-namespace: dedicated-server-deployment
  labels:
      app.kubernetes.io/managed-by: Helm
  name: efs-server-data
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08c85a185c3b5d475