version: "3"
volumes:
  zomboid-data:
services:
  barotrauma:
    image: barotrauma:latest
    build:
      context: .
      target: barotrauma-server
    ports:
      - 27015:27015
      - 27016:27016
    volumes:
      - ./barotrauma-data:/home/barotrauma-data
    command: ["/usr/games/steamcmd", "+force_install_dir /home/barotrauma-data", "+login anonymous", "+app_run 1026340"]
  zomboid:
    image: zomboid:latest
    build:
      context: .
      target: zomboid-server
    ports:
      - "16261:16261/udp"
      - "16262:16272/udp"
    volumes:
      - zomboid-data:/home/steam/zomboid-data