version: "3"
volumes:
  zomboid-data:
  valheim-data:
services:
  # barotrauma:
  #   image: barotrauma:latest
  #   build:
  #     context: .
  #     target: barotrauma-server
  #   ports:
  #     - 27015:27015
  #     - 27016:27016
  #   volumes:
  #     - ./barotrauma-data:/home/barotrauma-data
  #   command: ["/usr/games/steamcmd", "+force_install_dir /home/barotrauma-data", "+login anonymous", "+app_run 1026340"]
  zomboid:
    image: zomboid:latest
    build:
      context: .
      target: zomboid-server
    ports:
      - "16261:16261/udp"
      - "16262:16272/udp"
    volumes:
      - ./internal/Zomboid:/root/Zomboid
    command: ["zomboid-data/start-server.sh", "-servername", "NamonesWorld", "-adminpassword", "root"]
  valheim:
    image: valheim:latest
    build:
      context: .
      target: valheim-server
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    volumes:
      - valheim-data:/home/steam/valheim-data
