version: "3"
volumes:
  barotrauma-data:
services:
  barotrauma:
    image: barotrauma:latest
    build:
      context: .
      target: barotrauma-server
    volumes:
      - barotrauma-data:/home/steam/steamcmd/barotrauma-data
    command: ["sleep", "3600"]
