version: "3"
volumes:
  zomboid-data:
  valheim-data:
services:
  barotrauma:
    image: barotrauma
    command: ["/usr/games/steamcmd", "+force_install_dir", "/barotrauma", "+login", "anonymous", "+app_run", "1026340"]
    build:
      context: .
      target: barotrauma-server
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
  # zomboid:
  #   image: zomboid:latest
  #   build:
  #     context: .
  #     target: zomboid-server
  #   ports:
  #     - "16261:16261/udp"
  #     - "16262:16272/udp"
  #   volumes:
  #     - /internal/start-zomboid-server.sh:/home/valuser/start-zomboid-server.sh
  #     - zomboid-data:/root/Zomboid
  #   command: ["./start-zomboid-server.sh", "-servername", "NamonesWorld", "-adminpassword", "root"]
  # valheim:
  #   image: valheim:latest
  #   build:
  #     context: .
  #     target: valheim-server
  #   ports:
  #     - "2456:2456/udp"
  #     - "2457:2457/udp"
  #   volumes:
  #     - valheim-data:/root/.config
  #     - /internal/valheim/valuser:/home/valuser
  #     - /internal/valheim/Valheim:/root/.config/unity3d/IronGate/Valheim
  #   command: ["sleep", "9000"]
