version: "3"
volumes:
  barotrauma-data:
services:
  barotrauma:
    image: barotrauma:latest
    build:
      context: .
      target: barotrauma-server
    ports:
      - 27015:27015
      - 27016:27016
    volumes:
      - ./barotrauma-data:/home/barotrauma-data
    command: ["steamcmd", "+force_install_dir /home/barotrauma-data", "+login anonymous", "+app_run 1026340"]
