apiVersion: apps/v1
kind: Deployment
metadata:
    name: dedicated-server
    namespace: servers
spec:
    selector:
        matchLabels:
            app: dedicated-server
    template:
        metadata:
            labels:
                app: dedicated-server
        spec:
            # volumes:
              # - name: persistent-storage
              #   # This AWS EFS volume must already exist.
              #   persistentVolumeClaim:
              #     claimName: efs-claim
            volumes:  
              - name: storage-1
                persistentVolumeClaim:
                  claimName: claim-storage-1
              - name: storage-2
                persistentVolumeClaim:
                  claimName: claim-storage-2
            containers:
                - name: zomboid
                  image: {{ .Values.zomboidImage }}
                  imagePullPolicy: Always
                  command:
                    - "/usr/games/steamcmd"
                    - "+force_install_dir"
                    - "/home/pzuser/zomboid-data"
                    - "+login"
                    - "anonymous"
                    - "+app_update"
                    - "380870"
                    - "validate" 
                    - "+quit"
                    - "&&"
                    - "./zomboid-data/start-server.sh"
                    - "-servername"
                    - "NamonesWorld"
                    - "-adminpassword"
                    - "Muggins1"
                  ports:
                    - name: zomboid-server
                      protocol: UDP
                      containerPort: 16261
                    - name: zomb-server-q
                      protocol: UDP
                      containerPort: 16262
                  resources:
                      limits:
                        cpu: "2"
                        memory: 8Gi
                        ephemeral-storage: 32Gi
                      requests:
                        cpu: "1"
                        memory: 4Gi
                        ephemeral-storage: 8Gi
                  volumeMounts:
                    - name: storage-1
                      mountPath: /home/pzuser
                    - name: storage-2
                      mountPath: /root/Zomboid
                - name: valheim
                  image: {{ .Values.valheimImage }}
                  imagePullPolicy: Always
                  command:
                    - "sleep"
                    - "9000"
                  ports:
                    - name: valheim-server
                      protocol: UDP
                      containerPort: 2456
                    - name: val-server-q
                      protocol: UDP
                      containerPort: 2457
                  resources:
                      limits:
                        cpu: "2"
                        memory: 4Gi
                        ephemeral-storage: 4Gi
                      requests:
                        cpu: "1"
                        memory: 2Gi
                        ephemeral-storage: 2Gi
                  volumeMounts:
                    - name: storage-1
                      mountPath: /home/valuser
                    - name: storage-2
                      mountPath: /home/.config/unity3d/IronGate/Valheim/Worlds
            