apiVersion: apps/v1
kind: Deployment
metadata:
    name: dedicated-server
    namespace: servers
spec:
    selector:
        matchLabels:
            app: dedicated-server
    template:
        metadata:
            labels:
                app: dedicated-server
        spec:
            volumes:
            - name: game-data
              persistentVolumeClaim:
                claimName: efs-claim
            initContainers:
                # - name: init-zomboid
                #   image: {{ .Values.zomboidImage }}
                #   command: ["cp", "-rf", "/internal/ZomboidInstall", "/games/zomboid"]
                #   volumeMounts:
                #     - mountPath: /games/zomboid
                #       name: game-data
                # - name: init-pz-json
                #   image: {{ .Values.zomboidImage }}
                #   command: ["cp", "-rf", "/internal/ZomboidInstall/ProjectZomboid64.json", "/games/zomboid/ProjectZomboid64.json"]
                #   volumeMounts:
                #     - mountPath: /games/zomboid
                #       name: game-data
                # - name: init-pz-save
                #   image: {{ .Values.zomboidImage }}
                #   command: ["cp", "-rf", "/internal/Saves", "/games/save-data/Zomboid/Saves"]
                #   volumeMounts:
                #     - mountPath: /games/save-data/Zomboid/Saves
                #       name: game-data
                # - name: init-pz-conf
                #   image: {{ .Values.zomboidImage }}
                #   command: ["cp", "-rf", "/internal/Server", "/games/save-data/Zomboid/Server"]
                #   volumeMounts:
                #     - mountPath: /games/save-data/Zomboid/Server
                #       name: game-data
                # - name: init-pz-db
                #   image: {{ .Values.zomboidImage }}
                #   command: ["cp", "-rf", "/internal/db", "/games/save-data/Zomboid/db"]
                #   volumeMounts:
                #     - mountPath: /games/save-data/Zomboid/db
                #       name: game-data
                # - name: init-valheim
                #   image: {{ .Values.valheimImage }}
                #   command: ["mv", "/internal/ValheimInstall", "/games/valheim"]
                #   volumeMounts:
                #     - mountPath: /games/valheim
                #       name: game-data
                # - name: init-val-script
                #   image: {{ .Values.valheimImage }}
                #   command: ["mv", "/internal/start-valheim-server.sh", "/games/valheim/start-valheim-server.sh"]
                #   volumeMounts:
                #     - mountPath: /games/valheim/start-valheim-server.sh
                #       name: game-data
            containers:
                - name: zomboid
                  image: {{ .Values.zomboidImage }}
                  imagePullPolicy: Always
                  command:
                    - "./start-server.sh"
                    - "-servername"
                    - "zomboid"
                    - "-adminpassword"
                    - "Muggins1"
                  ports:
                    - name: zomboid-server
                      protocol: UDP
                      containerPort: 16261
                    - name: zomb-server-q
                      protocol: UDP
                      containerPort: 16262
                  resources:
                      limits:
                        cpu: "2"
                        memory: 8Gi
                        ephemeral-storage: 16Gi
                      requests:
                        cpu: "1"
                        memory: 2Gi
                        ephemeral-storage: 8Gi
                  volumeMounts:
                    - name: game-data
                      mountPath: /games
                - name: valheim
                  image: {{ .Values.valheimImage }}
                  imagePullPolicy: Always
                  command:
                    - "/bin/bash"
                    - "./start-valheim-server.sh"
                  ports:
                    - name: valheim-server
                      protocol: UDP
                      containerPort: 2456
                    - name: val-server-q
                      protocol: UDP
                      containerPort: 2457
                  resources:
                      limits:
                        cpu: "2"
                        memory: 4Gi
                        ephemeral-storage: 8Gi
                      requests:
                        cpu: "1"
                        memory: 2Gi
                        ephemeral-storage: 2Gi
                  volumeMounts:
                    - name: game-data
                      mountPath: /games
              