apiVersion: apps/v1
kind: Deployment
metadata:
    name: dedicated-server
    namespace: servers
spec:
    selector:
        matchLabels:
            app: dedicated-server
    template:
        metadata:
            labels:
                app: dedicated-server
        spec:
            # volumes:
              # - name: persistent-storage
              #   # This AWS EFS volume must already exist.
              #   persistentVolumeClaim:
              #     claimName: efs-claim
            volumes:  
              - name: pz-game-data
                persistentVolumeClaim:
                  claimName: pz-storage-1
              - name: pz-save-data
                persistentVolumeClaim:
                  claimName: pz-storage-2
              - name: val-game-data
                persistentVolumeClaim:
                  claimName: val-storage-1
              - name: val-save-data
                persistentVolumeClaim:
                  claimName: val-storage-2
            initContainers:
                - name: init-zomboid
                  image: {{ .Values.zomboidImage }}
                  command: ["/usr/games/steamcmd", "+force_install_dir", "/home/pzuser", "+login", "anonymous", "+app_update", "380870", "validate", "+quit"]
                  volumeMounts:
                    - mountPath: /home/pzuser
                      name: pz-game-data
                - name: init-pz-script
                  image: {{ .Values.zomboidImage }}
                  command: ["mv", "/internal/start-zomboid-server.sh", "/home/pzuser/start-zomboid-server.sh"]
                  volumeMounts:
                    - mountPath: /home/pzuser/start-zomboid-server.sh
                      name: pz-game-data
                - name: init-valheim
                  image: {{ .Values.valheimImage }}
                  command: ["/usr/games/steamcmd", "+force_install_dir", "/home/valuser", "+login", "anonymous", "+app_update", "896660", "validate", "+quit"]
                  volumeMounts:
                    - mountPath: /home/valuser
                      name: val-game-data
                - name: init-val-script
                  image: {{ .Values.valheimImage }}
                  command: ["mv", "/internal/start-valheim-server.sh", "/home/valuser/start-valheim-server.sh"]
                  volumeMounts:
                    - mountPath: /home/valuser/start-valheim-server.sh
                      name: val-game-data
            containers:
                - name: zomboid
                  image: {{ .Values.zomboidImage }}
                  imagePullPolicy: Always
                  command:
                    - "./start-zomboid-server.sh"
                    - "-servername"
                    - "NamonesLandOfWhimsy"
                    - "-adminpassword"
                    - "Muggins1"
                  ports:
                    - name: zomboid-server
                      protocol: UDP
                      containerPort: 16261
                    - name: zomb-server-q
                      protocol: UDP
                      containerPort: 16262
                  resources:
                      limits:
                        cpu: "2"
                        memory: 8Gi
                        ephemeral-storage: 16Gi
                      requests:
                        cpu: "1"
                        memory: 2Gi
                        ephemeral-storage: 8Gi
                  volumeMounts:
                    - name: pz-game-data
                      mountPath: /home/pzuser
                    - name: pz-save-data
                      mountPath: /root/Zomboid
                - name: valheim
                  image: {{ .Values.valheimImage }}
                  imagePullPolicy: Always
                  command:
                    - "/bin/bash"
                    - "./start-valheim-server.sh"
                  ports:
                    - name: valheim-server
                      protocol: UDP
                      containerPort: 2456
                    - name: val-server-q
                      protocol: UDP
                      containerPort: 2457
                  resources:
                      limits:
                        cpu: "2"
                        memory: 8Gi
                        ephemeral-storage: 8Gi
                      requests:
                        cpu: "1"
                        memory: 2Gi
                        ephemeral-storage: 2Gi
                  volumeMounts:
                    - name: val-game-data
                      mountPath: /home/valuser
                    - name: val-save-data
                      mountPath: /root/.config
              