apiVersion: apps/v1
kind: Deployment
metadata:
    name: barotrauma
    namespace: servers
spec:
    selector:
        matchLabels:
            app: barotrauma
    template:
        metadata:
            labels:
                app: barotrauma
        spec:
            containers:
                - name: barotrauma
                  image: {{ .Values.barotraumaImage }}
                  command:
                    - "/usr/games/steamcmd"
                    - "+force_install_dir /home/barotrauma-data" 
                    - "+login anonymous"
                    - "+app_run 1026340"
                  ports:
                    - containerPort: 27015
                  resources:
                      limits:
                        cpu: "0.1"
                  volumeMounts:
                    - mountPath: /home/steam/barotrauma-data
                      name: barotrauma-server-data
            volumes:
                - name: barotrauma-server-data
                  emptyDir: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: zomboid
    namespace: servers
spec:
    selector:
        matchLabels:
            app: zomboid
    template:
        metadata:
            labels:
                app: zomboid
        spec:
            volumes:  
              - name: server-data-storage
                persistentVolumeClaim:
                  claimName: server-data
            containers:
                - name: zomboid
                  image: {{ .Values.zomboidImage }}
                  command:
                    - "/bin/bash"
                    - "/home/steam/zomboid-data/start-server.sh"
                    - "-servername"
                    - "NamonesWorld"
                    - "-adminpassword"
                    - "root"
                  ports:
                    - name: zomboid-server
                      protocol: UDP
                      containerPort: 16261
                    - name: zomb-server-q
                      protocol: UDP
                      containerPort: 16262
                  resources:
                      limits:
                        cpu: "1"
                  volumeMounts:
                    - mountPath: /home/steam/zomboid-data
                      name: server-data-storage
                    - mountPath: /home/steam/Zomboid
                      name: server-data-storage