apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        meta.helm.sh/release-name: dedicated-server-endpoint
        meta.helm.sh/release-namespace: dedicated-server-endpoint
    generation: 1
    labels:
        app: dedicated-server-endpoint
        app.kubernetes.io/managed-by: Helm
    name: dedicated-server-endpoint
    namespace: servers
spec:
    rules:
        - host: barotrauma.namonesdedicatedserver.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: baro-server
                            port:
                                name: baro-server
        - host: zomboid.namonesdedicatedserver.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: zomboid-server
                            port:
                                name: zomboid-server
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: zomb-server-q
                            port:
                                name: zomb-server-q