apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
      meta.helm.sh/release-name: dedicated-server-deployment
      meta.helm.sh/release-namespace: dedicated-server-deployment
  labels:
      app.kubernetes.io/managed-by: Helm
  name: server-data
  namespace: servers
  labels:
    type: server-data
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/steam"